// 案例数据 - 全部54个案例
const cases = [
  {
    _id: 'case-yuanxian-xishi',
    featured: true,
    title: '西施笑 · 院线电影',
    category: '电影',
    coverUrl: '/images/covers/yuanxian-xishi-cover.jpg',
    images: ['/pages/casepkg/images/cases/yuanxian-xishi-cover.jpg', '/pages/casepkg/images/cases/yuanxian-xishi-1.jpg'],
    description: '院线电影《西施笑》，与刘佩琦、佟晨洁及导演周浩晖团队合作。',
    tags: ['院线电影', '灯光设计', '古装'],
    year: 2024,
    duration: '120分钟',
    role: '执行灯光师'
  },
  {
    _id: 'case-ai-jinling',
    featured: false,
    title: 'AI金陵 · AIGC作品',
    category: 'AIGC',
    coverUrl: '/images/covers/ai-jinling-cover.jpg',
    images: ['/pages/casepkg/images/cases/ai-jinling-cover.jpg', '/pages/casepkg/images/cases/ai-jinling-1.jpg', '/pages/casepkg/images/cases/ai-jinling-2.jpg'],
    description: 'AI辅助创作的南京城市影像，探索AI技术与影视美学的融合可能。',
    tags: ['AIGC', '城市影像', 'AI创作'],
    year: 2025,
    duration: '1分钟',
    role: '导演/AI制作'
  },
  {
    _id: 'case-ai-longteng',
    featured: false,
    title: '锦绣建邺·龙腾新春 · AI短片',
    category: 'AIGC',
    coverUrl: '/images/covers/ai-longteng-cover.jpg',
    images: ['/pages/casepkg/images/cases/ai-longteng-cover.jpg', '/pages/casepkg/images/cases/ai-longteng-1.jpg'],
    description: '南京建邺区新年宣传AI短片"锦绣建邺·龙腾新春"，实现AI生成与专业影视质感融合，展示城市文化魅力。',
    tags: ['AIGC', '城市宣传', 'AI短片'],
    year: 2025,
    duration: '1分钟',
    role: '导演/AI制作'
  },
  {
    _id: 'case-ai-manju',
    featured: false,
    title: 'AI漫剧 · 实验作品',
    category: 'AIGC',
    coverUrl: '/images/covers/ai-manju-cover.jpg',
    images: ['/pages/casepkg/images/cases/ai-manju-cover.jpg'],
    description: 'AI辅助生成的漫画风格短片，探索AIGC在叙事影像中的创作边界。',
    tags: ['AIGC', 'AI漫画', '实验影像'],
    year: 2025,
    duration: '2分钟',
    role: '导演/AI制作'
  },
  {
    _id: 'case-mv-tianwai',
    featured: false,
    title: '《天外来物》· MV',
    category: 'MV',
    coverUrl: '/images/covers/mv-tianwai-cover.jpg',
    images: ['/pages/casepkg/images/cases/mv-tianwai-cover.jpg', '/pages/casepkg/images/cases/mv-tianwai-1.jpg'],
    description: '音乐MV《天外来物》，以独特视觉语言诠释音乐情感。',
    tags: ['MV', '音乐', '创意影像'],
    year: 2024,
    duration: '4分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-mv-yinhe',
    featured: false,
    title: '《银河飞车》· MV',
    category: 'MV',
    coverUrl: '/images/covers/mv-yinhe-cover.jpg',
    images: ['/pages/casepkg/images/cases/mv-yinhe-cover.jpg', '/pages/casepkg/images/cases/mv-yinhe-1.jpg', '/pages/casepkg/images/cases/mv-yinhe-2.jpg'],
    description: '音乐MV《银河飞车》，充满想象力的视觉叙事与音乐节奏完美融合。',
    tags: ['MV', '音乐', '创意影像'],
    year: 2024,
    duration: '4分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-tvc-shangqi',
    featured: false,
    title: '上汽大通 · TVC广告',
    category: '影视制作',
    coverUrl: '/images/covers/tvc-shangqi-cover.jpg',
    images: ['/pages/casepkg/images/cases/tvc-shangqi-cover.jpg'],
    description: '上汽大通品牌TVC广告，专业拍摄制作，展现品牌调性与产品力。',
    tags: ['TVC', '品牌广告', '汽车'],
    year: 2025,
    duration: '60秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-tvc-langsheng',
    featured: false,
    title: '朗盛药业 · TVC广告',
    category: '影视制作',
    coverUrl: '/images/covers/tvc-langsheng-cover.jpg',
    images: ['/pages/casepkg/images/cases/tvc-langsheng-cover.jpg', '/pages/casepkg/images/cases/tvc-langsheng-1.jpg'],
    description: '朗盛药业品牌广告片，从创意策划到拍摄成片，展现企业形象与产品价值。',
    tags: ['TVC', '品牌广告', '医药'],
    year: 2025,
    duration: '60秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-tvc-lixiang',
    featured: false,
    title: '理想汽车 · TVC广告',
    category: '影视制作',
    coverUrl: '/images/covers/tvc-lixiang-cover.jpg',
    images: ['/pages/casepkg/images/cases/tvc-lixiang-cover.jpg', '/pages/casepkg/images/cases/tvc-lixiang-1.jpg'],
    description: '理想汽车品牌TVC广告拍摄，展现新能源出行方式与品牌理念。',
    tags: ['TVC', '品牌广告', '汽车'],
    year: 2025,
    duration: '60秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-tvc-changan',
    featured: false,
    title: '长安汽车 · TVC广告',
    category: '影视制作',
    coverUrl: '/images/covers/tvc-changan-cover.jpg',
    images: ['/pages/casepkg/images/cases/tvc-changan-cover.jpg', '/pages/casepkg/images/cases/tvc-changan-1.jpg'],
    description: '长安汽车品牌广告片，以专业影像展现产品质感与品牌魅力。',
    tags: ['TVC', '品牌广告', '汽车'],
    year: 2025,
    duration: '60秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-tvc-huangshan',
    featured: false,
    title: '黄山帐篷客酒店 · 宣传片',
    category: '宣传片',
    coverUrl: '/images/covers/tvc-huangshan-cover.jpg',
    images: ['/pages/casepkg/images/cases/tvc-huangshan-cover.jpg', '/pages/casepkg/images/cases/tvc-huangshan-1.jpg', '/pages/casepkg/images/cases/tvc-huangshan-2.jpg', '/pages/casepkg/images/cases/tvc-huangshan-3.jpg'],
    description: '黄山帐篷客酒店度假体验宣传片，以视觉叙事展现自然之美与度假生活方式。',
    tags: ['文旅', '酒店', '宣传片'],
    year: 2025,
    duration: '2分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-tcl-bingqilin',
    featured: true,
    title: 'TCL"冰麒麟" · AI创意片',
    category: 'AIGC',
    coverUrl: '/images/covers/tcl-bingqilin-cover.jpg',
    images: ['/pages/casepkg/images/cases/tcl-bingqilin-cover.jpg', '/pages/casepkg/images/cases/tcl-bingqilin-1.jpg'],
    description: 'TCL"冰麒麟"AI创意广告片，从概念策划到成片输出，完整实践AI辅助视频生产全流程，使用Seedance等主流AIGC工具。',
    tags: ['AIGC', 'AI短片', '品牌广告'],
    year: 2025,
    duration: '30秒',
    role: '导演/AI制作'
  },
  {
    _id: 'case-bujian-zhenwo',
    featured: false,
    title: '不见真我 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/bujian-zhenwo-cover.jpg',
    images: ['/pages/casepkg/images/cases/bujian-zhenwo-cover.jpg', '/pages/casepkg/images/cases/bujian-zhenwo-1.jpg', '/pages/casepkg/images/cases/bujian-zhenwo-2.jpg'],
    description: '独立短片，探讨自我认知与内心真实，以影像语言叩问存在的本质。',
    tags: ['独立短片', '哲学', '实验'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/剪辑'
  },
  {
    _id: 'case-yunlu-de-dongtian',
    featured: false,
    title: '云路街的冬天 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/yunlu-de-dongtian-cover.jpg',
    images: ['/pages/casepkg/images/cases/yunlu-de-dongtian-cover.jpg', '/pages/casepkg/images/cases/yunlu-de-dongtian-1.jpg'],
    description: '以南京云路街为背景的冬日故事，用镜头记录城市温度与人间烟火。',
    tags: ['独立短片', '城市', '冬日'],
    year: 2024,
    duration: '12分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-hudong-guangying',
    featured: true,
    title: '《光影人生》',
    category: '互动影游',
    coverUrl: '/images/case-guangying.jpg',
    images: ['/images/case-guangying.jpg', '/pages/casepkg/images/cases/hudong-guangying-1.jpg', '/pages/casepkg/images/cases/hudong-guangying-2.jpg'],
    description: '《光影人生》是一款集合了校园、恋爱、商战为一体的真人互动式电影游戏。玩家将作为男主角沈浩，经历从落魄到辉煌的过山车式人生体验。虽然身处尔虞我诈的商战中，但你并不孤独。朋友、恋人相伴左右，也是你人生道路上的一盏盏明灯。',
    tags: ['影视制作', '故事短片', '创意影像'],
    year: 2024,
    duration: '5分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-nide-daoying',
    featured: false,
    title: '你的倒影 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/nide-daoying-cover.jpg',
    images: ['/pages/casepkg/images/cases/nide-daoying-cover.jpg', '/pages/casepkg/images/cases/nide-daoying-1.jpg', '/pages/casepkg/images/cases/nide-daoying-2.jpg'],
    description: '以倒影为意象的独立短片，探索自我与他者的关系，入围多个电影节。',
    tags: ['独立短片', '人文', '艺术'],
    year: 2024,
    duration: '15分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-zaijian-mianbaoche',
    featured: false,
    title: '再见面包车 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/zaijian-mianbaoche-cover.jpg',
    images: ['/pages/casepkg/images/cases/zaijian-mianbaoche-cover.jpg', '/pages/casepkg/images/cases/zaijian-mianbaoche-1.jpg'],
    description: '以面包车为线索的公路题材短片，入围罗马棱镜电影节最佳影片单元。',
    tags: ['独立短片', '公路', '电影节入围'],
    year: 2024,
    duration: '12分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-zhi-zai-xuyu',
    featured: false,
    title: '只在须臾 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/zhi-zai-xuyu-cover.jpg',
    images: ['/pages/casepkg/images/cases/zhi-zai-xuyu-cover.jpg'],
    description: '捕捉瞬间之美的独立短片，以细腻的镜头语言探索时间的流逝与永恒。',
    tags: ['独立短片', '艺术', '实验'],
    year: 2024,
    duration: '8分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-kekong',
    featured: false,
    title: '可控 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/kekong-cover.jpg',
    images: ['/pages/casepkg/images/cases/kekong-cover.jpg', '/pages/casepkg/images/cases/kekong-1.jpg', '/pages/casepkg/images/cases/kekong-2.jpg', '/pages/casepkg/images/cases/kekong-3.jpg'],
    description: '探讨控制与自由的独立短片，以克制影像风格呈现深层主题。',
    tags: ['独立短片', '实验', '社会'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/剪辑'
  },
  {
    _id: 'case-huxi',
    featured: false,
    title: '呼吸 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/huxi-cover.jpg',
    images: ['/pages/casepkg/images/cases/huxi-cover.jpg'],
    description: '以呼吸为隐喻的实验短片，探索生命节奏与内心世界的关联。',
    tags: ['独立短片', '实验', '艺术'],
    year: 2024,
    duration: '8分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-hejie',
    featured: false,
    title: '和解 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/hejie-cover.jpg',
    images: ['/pages/casepkg/images/cases/hejie-cover.jpg', '/pages/casepkg/images/cases/hejie-1.jpg', '/pages/casepkg/images/cases/hejie-2.jpg', '/pages/casepkg/images/cases/hejie-3.jpg', '/pages/casepkg/images/cases/hejie-4.jpg'],
    description: '关于家庭与和解的温情短片，以细腻镜头捕捉人物内心变化。',
    tags: ['独立短片', '家庭', '温情'],
    year: 2024,
    duration: '15分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-sihai-weimen',
    featured: false,
    title: '四海为门 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/sihai-weimen-cover.jpg',
    images: ['/pages/casepkg/images/cases/sihai-weimen-cover.jpg', '/pages/casepkg/images/cases/sihai-weimen-1.jpg'],
    description: '独立执导短片，探索人文关怀与影像表达的融合，入围多个国际短片节。',
    tags: ['独立短片', '人文', '现实题材'],
    year: 2024,
    duration: '12分钟',
    role: '导演/编剧/剪辑'
  },
  {
    _id: 'case-fenjin-hainiu',
    featured: false,
    title: '奋进的海牛 · 纪录片',
    category: '纪录片',
    coverUrl: '/images/covers/fenjin-hainiu-cover.jpg',
    images: ['/pages/casepkg/images/cases/fenjin-hainiu-cover.jpg', '/pages/casepkg/images/cases/fenjin-hainiu-1.jpg', '/pages/casepkg/images/cases/fenjin-hainiu-2.jpg', '/pages/casepkg/images/cases/fenjin-hainiu-3.jpg', '/pages/casepkg/images/cases/fenjin-hainiu-4.jpg', '/pages/casepkg/images/cases/fenjin-hainiu-5.jpg', '/pages/casepkg/images/cases/fenjin-hainiu-6.jpg'],
    description: '记录海牛保护工作者的坚守与付出，以影像传递生态保护的力量。',
    tags: ['纪录片', '生态', '人文'],
    year: 2024,
    duration: '20分钟',
    role: '导演/摄影/剪辑'
  },
  {
    _id: 'case-xuanchuan-guzhuang',
    featured: false,
    title: '古装走秀 · 宣传片',
    category: '宣传片',
    coverUrl: '/images/covers/xuanchuan-guzhuang-cover.jpg',
    images: ['/pages/casepkg/images/cases/xuanchuan-guzhuang-cover.jpg', '/pages/casepkg/images/cases/xuanchuan-guzhuang-1.jpg'],
    description: '古装走秀活动宣传片，以精美画面展现传统文化与现代审美的碰撞。',
    tags: ['宣传片', '古装', '文化'],
    year: 2025,
    duration: '3分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-xuanchuan-hehai',
    featured: false,
    title: '河海大学 · 宣传片',
    category: '宣传片',
    coverUrl: '/images/covers/xuanchuan-hehai-cover.jpg',
    images: ['/pages/casepkg/images/cases/xuanchuan-hehai-cover.jpg', '/pages/casepkg/images/cases/xuanchuan-hehai-1.jpg'],
    description: '河海大学形象宣传片，展现校园风貌与学术精神。',
    tags: ['宣传片', '教育', '校园'],
    year: 2025,
    duration: '5分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-xuanchuan-hainan',
    featured: false,
    title: '海南市井小吃 · 宣传片',
    category: '宣传片',
    coverUrl: '/images/covers/xuanchuan-hainan-cover.jpg',
    images: ['/pages/casepkg/images/cases/xuanchuan-hainan-cover.jpg', '/pages/casepkg/images/cases/xuanchuan-hainan-1.jpg'],
    description: '海南特色市井小吃宣传片，以美食为线索展现地方文化魅力。',
    tags: ['宣传片', '美食', '文旅'],
    year: 2025,
    duration: '3分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-guanggao-zhonghai',
    featured: false,
    title: '中海地产 · 系列广告',
    category: '广告',
    coverUrl: '/images/covers/guanggao-zhonghai-cover.jpg',
    images: ['/pages/casepkg/images/cases/guanggao-zhonghai-cover.jpg', '/pages/casepkg/images/cases/guanggao-zhonghai-1.jpg'],
    description: '为中海地产制作系列品牌广告，展现地产品质与生活方式，兼具人文表达与商业质感。',
    tags: ['地产', '品牌广告', '系列广告'],
    year: 2025,
    duration: '30秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-guanggao-yingchen',
    featured: false,
    title: '南京影宸电箱 · 广告',
    category: '广告',
    coverUrl: '/images/covers/guanggao-yingchen-cover.jpg',
    images: ['/pages/casepkg/images/cases/guanggao-yingchen-cover.jpg'],
    description: '南京影宸电箱产品广告，专业拍摄展现产品细节与品牌调性。',
    tags: ['广告', '产品', '商业'],
    year: 2025,
    duration: '30秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-guanggao-zimaogang',
    featured: false,
    title: '自贸港大屏 · 广告',
    category: '广告',
    coverUrl: '/images/covers/guanggao-zimaogang-cover.jpg',
    images: ['/pages/casepkg/images/cases/guanggao-zimaogang-cover.jpg'],
    description: '自贸港大屏广告投放项目，视觉创意与专业拍摄相结合。',
    tags: ['广告', '大屏', '商业'],
    year: 2025,
    duration: '15秒',
    role: '导演/摄影'
  },
  {
    _id: 'case-dongri-jianNuan',
    featured: false,
    title: '当冬日渐暖 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/dongri-jianNuan-cover.jpg',
    images: ['/pages/casepkg/images/cases/dongri-jianNuan-cover.jpg', '/pages/casepkg/images/cases/dongri-jianNuan-1.jpg', '/pages/casepkg/images/cases/dongri-jianNuan-2.jpg', '/pages/casepkg/images/cases/dongri-jianNuan-3.jpg', '/pages/casepkg/images/cases/dongri-jianNuan-4.jpg', '/pages/casepkg/images/cases/dongri-jianNuan-5.jpg', '/pages/casepkg/images/cases/dongri-jianNuan-6.jpg'],
    description: '关注女性议题的现实题材短片，以细腻镜头语言捕捉人物内心变化。',
    tags: ['独立短片', '女性议题', '现实题材'],
    year: 2024,
    duration: '15分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-hushui-biangan',
    featured: false,
    title: '我想那片湖水变干 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/hushui-biangan-cover.jpg',
    images: ['/pages/casepkg/images/cases/hushui-biangan-cover.jpg', '/pages/casepkg/images/cases/hushui-biangan-1.jpg', '/pages/casepkg/images/cases/hushui-biangan-2.jpg', '/pages/casepkg/images/cases/hushui-biangan-3.jpg', '/pages/casepkg/images/cases/hushui-biangan-4.jpg'],
    description: '充满诗意的独立短片，以湖水为意象探索记忆与遗忘的主题。',
    tags: ['独立短片', '诗意', '实验'],
    year: 2024,
    duration: '12分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-wugui',
    featured: false,
    title: '无归 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/wugui-cover.jpg',
    images: ['/pages/casepkg/images/cases/wugui-cover.jpg', '/pages/casepkg/images/cases/wugui-1.jpg', '/pages/casepkg/images/cases/wugui-2.jpg', '/pages/casepkg/images/cases/wugui-3.jpg'],
    description: '现实题材独立短片，探讨归乡与离别的主题，入围洛杉矶短片国际电影节。',
    tags: ['独立短片', '现实', '电影节入围'],
    year: 2024,
    duration: '18分钟',
    role: '导演/编剧'
  },
  {
    _id: 'case-xingqisan-lanse',
    featured: false,
    title: '星期三是蓝色的 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/xingqisan-lanse-cover.jpg',
    images: ['/pages/casepkg/images/cases/xingqisan-lanse-cover.jpg', '/pages/casepkg/images/cases/xingqisan-lanse-1.jpg'],
    description: '以色彩为线索的独立短片，用视觉隐喻构建独特的叙事空间。',
    tags: ['独立短片', '色彩', '实验'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-meiyou-hua',
    featured: false,
    title: '没有花 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/meiyou-hua-cover.jpg',
    images: ['/pages/casepkg/images/cases/meiyou-hua-cover.jpg', '/pages/casepkg/images/cases/meiyou-hua-1.jpg', '/pages/casepkg/images/cases/meiyou-hua-2.jpg', '/pages/casepkg/images/cases/meiyou-hua-3.jpg', '/pages/casepkg/images/cases/meiyou-hua-4.jpg', '/pages/casepkg/images/cases/meiyou-hua-5.jpg'],
    description: '以"无花"为意象的独立短片，探讨缺失与存在的关系。',
    tags: ['独立短片', '文艺', '实验'],
    year: 2024,
    duration: '12分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-fuqin-sanwenshi',
    featured: false,
    title: '父亲的散文诗 · 短片',
    category: '短片',
    coverUrl: '/images/covers/fuqin-sanwenshi-cover.jpg',
    images: ['/pages/casepkg/images/cases/fuqin-sanwenshi-cover.jpg', '/pages/casepkg/images/cases/fuqin-sanwenshi-1.jpg', '/pages/casepkg/images/cases/fuqin-sanwenshi-2.jpg'],
    description: '以父爱为主题的温情短片，如散文诗般娓娓道来父子/父女情深。',
    tags: ['短片', '家庭', '温情'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-zhutou-daoyan',
    featured: false,
    title: '猪头导演 · 短片',
    category: '短片',
    coverUrl: '/images/covers/zhutou-daoyan-cover.jpg',
    images: ['/pages/casepkg/images/cases/zhutou-daoyan-cover.jpg', '/pages/casepkg/images/cases/zhutou-daoyan-1.jpg'],
    description: '幽默风格的短片作品，以轻松手法讲述有趣故事。',
    tags: ['短片', '幽默', '创意'],
    year: 2024,
    duration: '8分钟',
    role: '导演/编剧'
  },
  {
    _id: 'case-zhenxin-banjie',
    featured: false,
    title: '真心半解 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/zhenxin-banjie-cover.jpg',
    images: ['/pages/casepkg/images/cases/zhenxin-banjie-cover.jpg', '/pages/casepkg/images/cases/zhenxin-banjie-1.jpg'],
    description: '青春情感题材短片，入围多个国际电影节，探索年轻一代的情感表达。',
    tags: ['独立短片', '青春', '情感'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/剪辑'
  },
  {
    _id: 'case-duanju-liren',
    featured: false,
    title: '利刃玫瑰 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-liren-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-liren-cover.jpg'],
    description: '短剧《利刃玫瑰》，快节奏叙事与精彩表演相结合的商业短剧作品。',
    tags: ['短剧', '商业', '剧情'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-shengti',
    featured: false,
    title: '声替 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-shengti-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-shengti-cover.jpg'],
    description: '短剧《声替》，以声音为线索的悬疑故事，探索身份与真相。',
    tags: ['短剧', '悬疑', '剧情'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-tianjiang',
    featured: false,
    title: '天降五宝狐仙 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-tianjiang-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-tianjiang-cover.jpg'],
    description: '奇幻题材短剧《天降五宝狐仙》，融合东方神话与现代叙事。',
    tags: ['短剧', '奇幻', '古装'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-mishi',
    featured: false,
    title: '密室赏金 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-mishi-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-mishi-cover.jpg', '/pages/casepkg/images/cases/duanju-mishi-1.jpg'],
    description: '密室题材短剧，紧张刺激的氛围营造与节奏把控。',
    tags: ['短剧', '悬疑', '密室'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-wuji',
    featured: false,
    title: '无极归来 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-wuji-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-wuji-cover.jpg'],
    description: '古装奇幻短剧《无极归来》，大气场景与精彩武打的完美结合。',
    tags: ['短剧', '古装', '奇幻'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-xiaoyuan',
    featured: false,
    title: '校园解密大冒险 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-xiaoyuan-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-xiaoyuan-cover.jpg'],
    description: '校园题材冒险短剧，青春活力与悬疑解密元素相融合。',
    tags: ['短剧', '校园', '冒险'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-qiushui',
    featured: false,
    title: '秋水揽星河 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-qiushui-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-qiushui-cover.jpg', '/pages/casepkg/images/cases/duanju-qiushui-1.jpg'],
    description: '唯美古风短剧《秋水揽星河》，以诗意画面讲述动人故事。',
    tags: ['短剧', '古风', '唯美'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-duanju-keYan',
    featured: false,
    title: '科研女老师 · 短剧',
    category: '短剧',
    coverUrl: '/images/covers/duanju-keYan-cover.jpg',
    images: ['/pages/casepkg/images/cases/duanju-keYan-cover.jpg', '/pages/casepkg/images/cases/duanju-keYan-1.jpg'],
    description: '以科研女性为主角的短剧，展现当代知识女性的生活与情感。',
    tags: ['短剧', '都市', '女性'],
    year: 2025,
    duration: '多集',
    role: '导演/摄影'
  },
  {
    _id: 'case-jilupian-hainan',
    featured: false,
    title: '海南中元节 · 纪录片',
    category: '纪录片',
    coverUrl: '/images/covers/jilupian-hainan-cover.jpg',
    images: ['/pages/casepkg/images/cases/jilupian-hainan-cover.jpg', '/pages/casepkg/images/cases/jilupian-hainan-1.jpg'],
    description: '记录海南中元节传统民俗活动，以影像保存文化遗产。',
    tags: ['纪录片', '民俗', '文化'],
    year: 2024,
    duration: '15分钟',
    role: '导演/摄影/剪辑'
  },
  {
    _id: 'case-jilupian-hupan',
    featured: false,
    title: '湖畔知音合唱团 · 纪录片',
    category: '纪录片',
    coverUrl: '/images/covers/jilupian-hupan-cover.jpg',
    images: ['/pages/casepkg/images/cases/jilupian-hupan-cover.jpg', '/pages/casepkg/images/cases/jilupian-hupan-1.jpg', '/pages/casepkg/images/cases/jilupian-hupan-2.jpg', '/pages/casepkg/images/cases/jilupian-hupan-3.jpg'],
    description: '记录湖畔知音合唱团的音乐故事，以镜头捕捉音乐与人的和谐共鸣。',
    tags: ['纪录片', '音乐', '人文'],
    year: 2024,
    duration: '20分钟',
    role: '导演/摄影/剪辑'
  },
  {
    _id: 'case-jilupian-niujin',
    featured: false,
    title: '牛津大学春晚 · 纪录片',
    category: '纪录片',
    coverUrl: '/images/covers/jilupian-niujin-cover.jpg',
    images: ['/pages/casepkg/images/cases/jilupian-niujin-cover.jpg', '/pages/casepkg/images/cases/jilupian-niujin-1.jpg'],
    description: '记录牛津大学中国学生春节联欢晚会，展现海外学子的文化自信与家国情怀。',
    tags: ['纪录片', '海外', '文化'],
    year: 2024,
    duration: '15分钟',
    role: '导演/摄影/剪辑'
  },
  {
    _id: 'case-zongyi-youman',
    featured: false,
    title: '优漫卡通卫视 · 综艺拍摄',
    category: '综艺',
    coverUrl: '/images/covers/zongyi-youman-cover.jpg',
    images: ['/pages/casepkg/images/cases/zongyi-youman-cover.jpg', '/pages/casepkg/images/cases/zongyi-youman-1.jpg'],
    description: '江苏广播电视集团优漫卡通卫视儿童综艺节目，负责外勤拍摄统筹与后期剪辑。',
    tags: ['综艺', '江苏广电', '拍摄统筹'],
    year: 2023,
    duration: '多期',
    role: '摄影/统筹'
  },
  {
    _id: 'case-laojie-xinxiang',
    featured: false,
    title: '老街新巷 · 纪录短片',
    category: '纪录片',
    coverUrl: '/images/covers/laojie-xinxiang-cover.jpg',
    images: ['/pages/casepkg/images/cases/laojie-xinxiang-cover.jpg', '/pages/casepkg/images/cases/laojie-xinxiang-1.jpg'],
    description: '人文纪录短片，记录城市老街巷的变迁与居民生活，以镜头留住城市记忆。',
    tags: ['纪录片', '人文', '城市'],
    year: 2024,
    duration: '8分钟',
    role: '导演/摄影/剪辑'
  },
  {
    _id: 'case-chishou-kongquan',
    featured: false,
    title: '赤手空拳 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/chishou-kongquan-cover.jpg',
    images: ['/pages/casepkg/images/cases/chishou-kongquan-cover.jpg', '/pages/casepkg/images/cases/chishou-kongquan-1.jpg'],
    description: '以奋斗为主题的独立短片，展现年轻人在困境中不屈不挠的精神。',
    tags: ['独立短片', '励志', '现实'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-yangguang-jiemei',
    featured: false,
    title: '阳光姐妹淘 · 短片',
    category: '短片',
    coverUrl: '/images/covers/yangguang-jiemei-cover.jpg',
    images: ['/pages/casepkg/images/cases/yangguang-jiemei-cover.jpg'],
    description: '青春友情题材短片，记录女孩们的阳光时光与成长故事。',
    tags: ['短片', '青春', '友情'],
    year: 2024,
    duration: '10分钟',
    role: '导演/摄影'
  },
  {
    _id: 'case-heidong',
    featured: false,
    title: '黑洞 · 独立短片',
    category: '短片',
    coverUrl: '/images/covers/heidong-cover.jpg',
    images: ['/pages/casepkg/images/cases/heidong-cover.jpg', '/pages/casepkg/images/cases/heidong-1.jpg', '/pages/casepkg/images/cases/heidong-2.jpg'],
    description: '科幻题材独立短片，以黑洞为隐喻探索人性深处。',
    tags: ['独立短片', '科幻', '实验'],
    year: 2024,
    duration: '12分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-xiaocheng-gushi9',
    featured: false,
    title: '小城故事多 · 短片',
    category: '短片',
    coverUrl: '/images/covers/xiaocheng-gushi9-cover.jpg',
    images: ['/pages/casepkg/images/cases/xiaocheng-gushi9-cover.jpg', '/pages/casepkg/images/cases/xiaocheng-gushi9-1.jpg'],
    description: '小城故事系列短片，以温情镜头讲述小城人物与故事。',
    tags: ['短片', '小城', '人文'],
    year: 2024,
    duration: '10分钟',
    role: '导演/编剧/摄影'
  },
  {
    _id: 'case-wuwu9',
    featured: false,
    title: '无无 · 短片',
    category: '短片',
    coverUrl: '/images/covers/wuwu9-cover.jpg',
    images: ['/pages/casepkg/images/cases/wuwu9-cover.jpg', '/pages/casepkg/images/cases/wuwu9-1.jpg', '/pages/casepkg/images/cases/wuwu9-2.jpg'],
    description: '实验性短片，探索影像叙事的边界与可能。',
    tags: ['短片', '实验', '先锋'],
    year: 2024,
    duration: '8分钟',
    role: '导演/编剧'
  }
]

// 报价配置 - 每个服务有独立的附加服务和定价规则
const quoteConfig = {
  // 所有可用附加服务（按ID索引）
  allAddons: {
    'drone':      { id: 'drone',   name: '航拍',       price: 800,  unit: '次', pricingType: 'fixed' },
    'script':     { id: 'script',  name: '脚本策划',   price: 1500, unit: '项', pricingType: 'fixed' },
    'actor':      { id: 'actor',   name: '演员',       price: 1500, unit: '人', pricingType: 'fixed' },
    'ad-monitor': { id: 'ad-monitor', name: '投流盯盘', price: 500, unit: '月', pricingType: 'perQuantity', note: '投流花费实报实销' },
    'photo-live': { id: 'photo-live', name: '图片直播', price: 600, unit: '次', pricingType: 'fixed' },
    'video-edit': { id: 'video-edit', name: '视频剪辑', price: 200, unit: '分钟', pricingType: 'perAddonQty' },
    'extra-actor':{ id: 'extra-actor', name: '额外演员', price: 500, unit: '人/天', pricingType: 'threshold', threshold: 5, note: '超过5人，每多1人+500/天' },
    'extra-scene':{ id: 'extra-scene', name: '额外场景', price: 800, unit: '个/天', pricingType: 'threshold', threshold: 4, note: '超过4个，每多1个+800/天' },
    'vfx':        { id: 'vfx',     name: '后期特效',   price: 0,   unit: '项', pricingType: 'custom', note: '费用另算' },
    'orig-music': { id: 'orig-music', name: '原创音乐', price: 120, unit: '分钟', pricingType: 'perAddonQty' }
  },
  // 每个服务对应的附加服务ID列表
  serviceAddons: {
    'propaganda':  ['drone', 'script', 'actor'],
    'tvc':         ['drone', 'script', 'actor'],
    'short-video': ['ad-monitor'],
    'event':       ['photo-live', 'video-edit'],
    'short-film':  ['extra-actor', 'extra-scene', 'vfx', 'orig-music']
  },
  // 服务列表
  services: [
    {
      id: 'propaganda',
      name: '宣传片',
      icon: '🎬',
      description: '企业宣传片、城市宣传片、产品宣传片',
      note: '学生作品、非商业用途价格面议',
      basePrice: 6000,
      priceLabel: '¥6000起',
      unitLabel: '1分钟',
      configType: 'duration',
      durationLabel: '时长（分钟）',
      durationUnit: '分钟',
      durationMin: 1
    },
    {
      id: 'tvc',
      name: 'TVC广告',
      icon: '📺',
      description: '品牌TVC、产品广告、信息流广告',
      note: '学生作品、非商业用途价格面议',
      basePrice: 8000,
      priceLabel: '¥8000起',
      unitLabel: '1分钟',
      configType: 'duration',
      durationLabel: '时长（分钟）',
      durationUnit: '分钟',
      durationMin: 1
    },
    {
      id: 'short-video',
      name: '短视频代运营',
      icon: '📱',
      description: '账号运营、内容策划、拍摄剪辑',
      basePrice: 1999,
      priceLabel: '¥1999起',
      unitLabel: '月',
      configType: 'plan',
      plans: [
        { id: 'monthly',    name: '月度套餐', price: 1999, unit: '月', desc: '20条信息流拍剪 或 40条纯剪辑' },
        { id: 'half_year',  name: '半年套餐', price: 1500, unit: '月', desc: '一次下单6个月' },
        { id: 'yearly',     name: '包年套餐', price: 1299, unit: '月', desc: '一次性包年' }
      ]
    },
    {
      id: 'event',
      name: '活动纪录',
      icon: '📹',
      description: '会议纪录、活动直播、展会拍摄',
      basePrice: 800,
      priceLabel: '¥800起',
      unitLabel: '4小时',
      configType: 'durationToggle',
      durationOptions: [
        { id: 'half', name: '4小时', price: 800 },
        { id: 'full', name: '一天(8h)', price: 1500 }
      ]
    },
    {
      id: 'short-film',
      name: '短片/微电影',
      icon: '🎥',
      description: '品牌微电影、故事短片、创意短片',
      basePrice: 8000,
      priceLabel: '¥8000起',
      unitLabel: '5分钟内',
      configType: 'duration',
      durationLabel: '时长（分钟）',
      durationUnit: '分钟',
      durationMin: 1
    }
  ]
}

module.exports = { cases, quoteConfig }
